# Generated by Django 2.2.5 on 2019-09-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='cosmetics.Review'),
        ),
    ]
